### ISSUE TITLE
Return only subsets of the data

### ISSUE THREAD

**Issue by Erik-Roth** [thatsprettyfaroutman/simple-covid19-json-fetcher#1]
React noob here. I have been playing with the sandbox and trying to figure out a couple of things. 1.) I am trying to figure out how to properly use the entryMutator function, and 2.) How to return only subsets of data. On the subsets, the example I am referencing is  a return and print to console of "US", "particular state", so like US >> Idaho. No other data just the subset. Looking through the code I am sure it's possible, I am just not well versed enough in React - So sorry for being a noob!

**Comment by thatsprettyfaroutman** [comment]
Hey! I hope I understand correctly. So you want the result to only include, for example, Idaho or let's say Idaho and Utah. You are on the right tracks, you can achieve this with the `entryMutator` function. 

Here's an example (assuming you're using an async function):

```javascript
const usIdahoAndUtah = await covid19Fetcher(new Date(), {
  entryMutator: entry => {
    if (entry.provinceState === 'Idaho' || entry.provinceState === 'Utah') {
      return entry
    }
  }
})
```

Only the entries returned from the `entryMutator` function are kept, others are discarded.
Above example will result with the following dataset:

```javascript
[
  {
    "name": "US",
    "states": [
      {
        "name": "Idaho",
        "confirmed": 146,
        "deaths": 3,
        "recovered": 0,
        "active": 143,
        "latitude": 43.4526575,
        "longitude": -116.24155159999998,
        "lastUpdate": "2020-03-26 23:48:35"
      },
      {
        "name": "Utah",
        "confirmed": 396,
        "deaths": 1,
        "recovered": 0,
        "active": 395,
        "latitude": 38.35657051,
        "longitude": -113.2342232,
        "lastUpdate": "2020-03-26 23:48:35"
      }
    ],

    // The following items only contain the combined data of Idaho and Utah. 
    "confirmed": 542,
    "deaths": 4,
    "recovered": 0,
    "active": 538,

    "latitude": 41.851358595810815,
    "longitude": -111.79096034054051,
    "lastUpdate": "2020-03-26 23:48:35"
  }
]
```



If you want only the states' data, you can go further by adding something like this:

```javascript
const states = usIdahoAndUtah && usIdahoAndUtah[0] && usIdahoAndUtah[0].states

/*
states === [
  {
    "name": "Idaho",
     ...
  },
  {
    "name": "Utah",
     ...
  }
]
*/
```

[CodeSandBox Example](https://codesandbox.io/s/wizardly-minsky-3j7z9)

Hope this helps!
